# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  myweatherforecast:
    image: myweatherforecast
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 1947:1947
